DROP TABLE STUDENT;

CREATE TABLE STUDENT(
    NAME VARCHAR2(50),
    AGE NUMBER,
    JAVA VARCHAR2(50),
    ORACLE VARCHAR2(50)
);

INSERT INTO STUDENT VALUES('이유나', 20, 'A+', 'C');
INSERT INTO STUDENT VALUES('김현우', 23, 'B+', 'A');
INSERT INTO STUDENT VALUES('이지원', 21, 'F', 'A+');

SELECT * FROM STUDENT;

COMMIT;